### ISSUE TITLE
Simplify writing

### ISSUE THREAD

**Issue by dwsinger** [WebStandardsFuture/Vision#25]
In

> We have treated the Web as a force for good

who is we? Do we need this circumlocution (which I think I wrote)?

Say

> The Web is a force for good

**Comment by michaelchampion** [comment]
How about "The web **can be** a force for good?  The whole point of the next sentence is that it is NOT unequivocally a force for good.

**Comment by TzviyaSiegman** [comment]
I think the point is that the W3C has historically assumed that the Web is a force for good, and we need to change that. What about "The W3C has treated the Web as (or assumed the Web is) a force for good."?

**Comment by dwsinger** [comment]
Saying that it is a force for good is true; it also has problems, but we don't "exclusively" a force for good
