### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by LJWatson** [WebStandardsFuture/Vision#4]
The vision document is beautifully written, but it includes a few words and phrases that may be difficult for some people to recognise or understand ("substrate", "cherry picking", "first and foremost" for examples). 

If a PR with proposed edits would be welcome, let me know.

**Comment by michaelchampion** [comment]
Thanks @LJWatson, a PR to improve readability would be appreciated.  I know at some level that I use too many long words and culture-specific allusions, but my fingers keep typing them :-) 

FWIW, I just ran the readme for this repo through a couple of style checkers, and neither flagged "cherry-picking" or "substrate" ... so a review by a human would be helpful.

**Comment by cwilso** [comment]
Closed due to the merged PR.
