### ISSUE TITLE
Is this ready to move to AB-public?

### ISSUE THREAD

**Issue by cwilso** [WebStandardsFuture/Vision#44]
Please thumbs-up here if you think it is, thumbs-down and comment below what you think needs to be done.

**Comment by dwsinger** [comment]
I'm fine with the move, but as I commented in the meeting, it needs separating into 
* What are we doing for the world
* How do we work

There are both in there, mixed up. Ensuring test suites is about how we work. The sections on Identity, Strategic Goals, and Purpose are mostly about our vision of who we are and how we work, not about what we're doing for society. They are equally important, but the document needs at least a clear separation, if not a split.

We can do this factoring before or after the move.

**Comment by avneeshsingh** [comment]
+1 for moving it to AB public.
This document is a good collection of principles that W3C community should follow. I think that we have done a very good job in collecting the principles.
We have also created a very nice "purpose of existence".
. We need to do more work for formulating compelling vision and mission statements.
As @dwsinger mentioned, we need to decide if we should be having vision for the web, vision for W3C or may be both.
I would say that we should have very broad vision for the web, and the vision and mission statement for W3C should highlight what role W3C intends to play in achieving the vision for the web.

**Comment by cwilso** [comment]
Done, moved to https://github.com/w3c/AB-public/tree/main/Vision.
