### ISSUE TITLE
Move/remove the history

### ISSUE THREAD

**Issue by LJWatson** [WebStandardsFuture/Vision#6]
I think this vision is thoughtfully written, but no matter how much thought goes into these things, recapping history is close to impossible because people always remember things differently. A lot of time could be spent trying to find words that work for everyone, likely without ever entirely succeeding, but it would be a huge distraction from this vision gaining adoption - so I'd like to suggest that the parts of the vision that recap history are removed (or possibly relocated).

**Comment by cwilso** [comment]
https://github.com/WebStandardsFuture/Vision/pull/9 moved the history to the end, but I'm planning on separating it out into a separate doc, so I'll leave this open for now.

**Comment by cwilso** [comment]
Fixed by https://github.com/WebStandardsFuture/Vision/commit/f0d6c4d416adb5ed8df9c08b6857e08620fe5dbd.
